// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuc7vUzuXgb14NeQlaritPffQMoC-b9U4',
    appId: '1:372513038054:web:1c864471ea63c654e5e527',
    messagingSenderId: '372513038054',
    projectId: 'fypckd',
    authDomain: 'fypckd.firebaseapp.com',
    storageBucket: 'fypckd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnNhUx2Hhu7-YhTLSCdHk7RqZKK4MBXT4',
    appId: '1:372513038054:android:eed0d9fdb9a34bf7e5e527',
    messagingSenderId: '372513038054',
    projectId: 'fypckd',
    storageBucket: 'fypckd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWUeTZvn9DWevQ4YL1SrzTi-m5kH-OYC8',
    appId: '1:372513038054:ios:d4f35747b3d70d5ee5e527',
    messagingSenderId: '372513038054',
    projectId: 'fypckd',
    storageBucket: 'fypckd.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWUeTZvn9DWevQ4YL1SrzTi-m5kH-OYC8',
    appId: '1:372513038054:ios:9675f768c6da0372e5e527',
    messagingSenderId: '372513038054',
    projectId: 'fypckd',
    storageBucket: 'fypckd.appspot.com',
    iosBundleId: 'com.example.fyp.RunnerTests',
  );
}
